### ISSUE TITLE
Very cool! A few questions

### ISSUE THREAD

**Issue by keithmgould** [gottliebtfreitag/inspexel#2]
1.  Wondering what you think the pros/cons are for inxpexel vs native (Robotis) library and tools?
2. For users of embedded systems (Arduino in my case) would you recommend your library? 
3. If yes to above, would it be possible for you to write a small test file showcasing basic functionality?

I think the answers to above questions would make great additions to README or WIKI. apologies if I missed the answers to these somewhere else...

**Comment by SGSSGene** [comment]
Hi @keithmgould
Yes, it seems like more explanation what inspexel is about is missing.
There is a short description on [discourse.ros.org](https://discourse.ros.org/t/inspexel-the-swiss-army-knife-for-dynamixel-servo-motors/6747). I guess some info should be adopted in our README.

A quick overview: Inspexel is a command line tool for linux. The tools from robotis are mostly windows centric and have heavy UI. The goal of inspexel is to have a slim command line tool to inspect your connected dynamixel motors. It also gives you the ability to use it inside of a (bash-)script.

Inspexel is not a library but it implements all details to use dynamixel motors. Also many implementation details are based on linux and c++17. Since the standard Arduino toolchain is not always up-to-date I could imagine it is much easier to start with the provided RobotisSDK.

I appreciate your interest and your feedback is very helpful.
Thank you

**Comment by SGSSGene** [comment]
Added 'introduction' to README. I hope this makes this purpose of this project clearer.
